### ISSUE TITLE
result

### ISSUE THREAD

**Issue by yang-W517** [jzchenriver/PIN-DGA#2]
How can I get the results of my trained data, and in which directory are they stored?

**Comment by jzchenriver** [comment]
如果是在自己构建的数据集上训练，需要在train.py中修改train_dataset参数为自建数据集的名字，训练的权重保存在result/PIN-DGA/[你的数据集名字]/中。
在inference.py中修改model参数为权重的路径，运行，得到每一幅检测结果的图像，保存在datasets/test_img/test_img_[测试数据集名字]/PIN-DGA-[训练数据集名字]/。
在get_metrics.py中修改train_dataset参数为训练数据集的名字，运行，得到指标。

**Comment by jzchenriver** [comment]
If training on a custom-built dataset, you need to modify the `train_dataset` parameter in `train.py` to the name of your custom dataset. The trained weights will be saved in the directory `result/PIN-DGA/[your dataset name]/`.  

In `inference.py`, update the `model` parameter to the path of the weights, run the script, and you will obtain the detection results for each image. The results will be saved in the directory `datasets/test_img/test_img_[test dataset name]/PIN-DGA-[training dataset name]/`.  

In `get_metrics.py`, modify the `train_dataset` parameter to the name of the training dataset and run the script to obtain the evaluation metrics.
